// AUTO-GENERATED by vite plugin. Do not edit.
import type { AppType } from './server';

export type PageName = 'Faq' | 'Home' | 'Item/Show' | 'Ranking' | 'Readme';

declare module '../src/page-props' {
  interface AppRegistry {
    app: AppType;
  }
}

export type { PageProps } from '../src/page-props';
